services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GUNICORN_PORT}:${GUNICORN_PORT}"
    volumes:
      - .:/app
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn drf.wsgi --bind ${GUNICORN_ADDRESS}:${GUNICORN_PORT}
            "
