# Generated by Django 5.0.7 on 2024-10-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="status",
        ),
    ]
