name: Python CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linters (flake8)
      run: flake8 .

    - name: Check code formatting (black)
      run: black --check .

    - name: Sort imports (isort)
      run: isort --check-only .

    - name: Run tests (pytest)
      run: pytest
